R"(<!DOCTYPE html>
<head>
<title>gitgen index</title>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body>
<div id="content">
<table cellspacing="0" cellpadding="2" id="repos">
<thead>
<tr class="toptr">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Author</th>
<th style="text-align: left;">Updated</th>
<tr>
</thead>
<tbody>
{repos_content}
</tbody>
</table>
</div>
</body>
</html>)"
